#!/usr/bin/env python3
"""
setup_afa.py - Universal Cross-Platform Setup Script for AFA (Autonomous Financial Advisor)

This script auto-detects the user's OS, verifies prerequisites, clones the repo,
and prepares the Docker environment.

Requirements:
- Python 3.7+
- git
- Docker Desktop / Docker Engine
- docker compose (v2)
"""

import os
import sys
import subprocess
import platform
import shutil
from pathlib import Path
from typing import Tuple, Optional

# ============================================================================
# Configuration
# ============================================================================
REPO_URL = "https://github.com/p8rtm3sh/afa.git"
PROJECT_DIR_NAME = "afa"
REQUIRED_DIRS = ["data", "output", "logs", "airflow/dags", "airflow/logs", "airflow/plugins"]
AIRFLOW_UID = 50000
AIRFLOW_GID = 0

DEFAULT_ENV_CONTENT = """# AFA Environment Configuration
# Generated by setup_afa.py

# Timezone
TZ=Asia/Kolkata

# Portfolio Configuration
PA_PORTFOLIO_VALUE_INR=308733
PA_RISK_PER_TRADE_PCT=0.01

# Trading Mode
PA_PAPER_TRADING_MODE=true

# Airflow Configuration
AIRFLOW__CORE__EXECUTOR=LocalExecutor
AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
"""

# ============================================================================
# Color Output Helpers
# ============================================================================
class Colors:
    """ANSI color codes for terminal output."""
    RESET = "\033[0m"
    BOLD = "\033[1m"
    RED = "\033[91m"
    GREEN = "\033[92m"
    YELLOW = "\033[93m"
    BLUE = "\033[94m"
    MAGENTA = "\033[95m"
    CYAN = "\033[96m"
    WHITE = "\033[97m"

def print_banner():
    """Print a colorful banner."""
    banner = """
╔═══════════════════════════════════════════════════════════╗
║                                                           ║
║     🚀  AFA (Autonomous Financial Advisor) Setup Script   ║
║                                                           ║
╚═══════════════════════════════════════════════════════════╝
"""
    print(Colors.CYAN + Colors.BOLD + banner + Colors.RESET)

def print_success(message: str):
    """Print a success message in green."""
    print(f"{Colors.GREEN}✓{Colors.RESET} {message}")

def print_error(message: str):
    """Print an error message in red."""
    print(f"{Colors.RED}✗{Colors.RESET} {message}")

def print_warning(message: str):
    """Print a warning message in yellow."""
    print(f"{Colors.YELLOW}⚠{Colors.RESET} {message}")

def print_info(message: str):
    """Print an info message in blue."""
    print(f"{Colors.BLUE}ℹ{Colors.RESET} {message}")

def print_section(message: str):
    """Print a section header."""
    print(f"\n{Colors.MAGENTA}{Colors.BOLD}=== {message} ==={Colors.RESET}\n")

# ============================================================================
# System Detection
# ============================================================================
def get_os() -> str:
    """Detect and return the operating system."""
    system = platform.system()
    if system == "Windows":
        return "windows"
    elif system == "Darwin":
        return "macos"
    elif system == "Linux":
        return "linux"
    else:
        return "unknown"

def get_os_display_name() -> str:
    """Get a human-readable OS name."""
    os_name = get_os()
    if os_name == "windows":
        return "Windows"
    elif os_name == "macos":
        return "macOS"
    elif os_name == "linux":
        return "Linux"
    else:
        return f"Unknown ({platform.system()})"

# ============================================================================
# Prerequisites Check
# ============================================================================
def run_command(cmd: list, capture_output: bool = True, check: bool = False) -> Tuple[int, str, str]:
    """
    Run a shell command and return exit code, stdout, stderr.
    
    Args:
        cmd: Command as list of strings
        capture_output: Whether to capture stdout/stderr
        check: Whether to raise exception on non-zero exit
    
    Returns:
        Tuple of (exit_code, stdout, stderr)
    """
    try:
        result = subprocess.run(
            cmd,
            capture_output=capture_output,
            text=True,
            check=check
        )
        return result.returncode, result.stdout or "", result.stderr or ""
    except subprocess.CalledProcessError as e:
        return e.returncode, e.stdout or "", e.stderr or ""
    except FileNotFoundError:
        return -1, "", f"Command not found: {cmd[0]}"

def check_git() -> bool:
    """Check if git is installed and accessible."""
    print_info("Checking for git...")
    exit_code, stdout, stderr = run_command(["git", "--version"])
    if exit_code == 0:
        print_success(f"Git found: {stdout.strip()}")
        return True
    else:
        print_error("Git is not installed or not in PATH")
        return False

def check_docker() -> bool:
    """Check if Docker is installed and daemon is running."""
    print_info("Checking for Docker...")
    exit_code, stdout, stderr = run_command(["docker", "info"])
    if exit_code == 0:
        print_success("Docker is installed and running")
        return True
    else:
        print_error("Docker is not installed or daemon is not running")
        if stderr:
            print_warning(f"Docker error: {stderr.strip()}")
        return False

def check_docker_compose() -> bool:
    """Check if docker compose (v2) is available."""
    print_info("Checking for Docker Compose (v2)...")
    # Try 'docker compose' (v2 syntax)
    exit_code, stdout, stderr = run_command(["docker", "compose", "version"])
    if exit_code == 0:
        print_success(f"Docker Compose found: {stdout.strip()}")
        return True
    
    # Fallback: try 'docker-compose' (v1 syntax)
    exit_code, stdout, stderr = run_command(["docker-compose", "--version"])
    if exit_code == 0:
        print_warning(f"Docker Compose (v1) found: {stdout.strip()}")
        print_info("Consider upgrading to Docker Compose v2 ('docker compose')")
        return True
    
    print_error("Docker Compose is not installed")
    return False

def print_installation_guide(os_name: str):
    """Print OS-specific installation guide for missing prerequisites."""
    print_section("Installation Guide")
    
    guides = {
        "windows": """
To install the required software on Windows:

1. Git:
   - Download from: https://git-scm.com/download/win
   - Run the installer and follow the wizard
   - Ensure "Git Bash Here" is selected during installation

2. Docker Desktop:
   - Download from: https://www.docker.com/products/docker-desktop/
   - Run Docker Desktop Installer.exe
   - Enable WSL 2 backend when prompted
   - Restart your computer after installation

3. Docker Compose (included with Docker Desktop):
   - Docker Desktop includes Docker Compose v2 automatically
   - Verify with: docker compose version

After installation, restart your terminal and run this script again.
""",
        "macos": """
To install the required software on macOS:

1. Git:
   - Install Xcode Command Line Tools:
     $ xcode-select --install
   - Or install via Homebrew:
     $ brew install git

2. Docker Desktop:
   - Download from: https://www.docker.com/products/docker-desktop/
   - Open Docker.dmg and drag Docker to Applications
   - Launch Docker Desktop from Applications folder

3. Docker Compose (included with Docker Desktop):
   - Docker Desktop includes Docker Compose v2 automatically
   - Verify with: docker compose version

Alternatively, using Homebrew:
   $ brew install --cask docker
   
After installation, restart your terminal and run this script again.
""",
        "linux": """
To install the required software on Linux:

1. Git:
   Ubuntu/Debian:
     $ sudo apt update && sudo apt install -y git
   Fedora/RHEL:
     $ sudo dnf install -y git
   Arch:
     $ sudo pacman -S git

2. Docker Engine:
   Ubuntu/Debian:
     $ curl -fsSL https://get.docker.com | sh
     $ sudo systemctl enable docker
     $ sudo systemctl start docker
   Fedora/RHEL:
     $ sudo dnf -y install dnf-plugins-core
     $ sudo dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
     $ sudo dnf install -y docker-ce docker-ce-cli containerd.io
     $ sudo systemctl enable docker
     $ sudo systemctl start docker

3. Docker Compose (v2):
   Download from: https://docs.docker.com/compose/install/linux/
   Or use the official script:
     $ sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
     $ sudo chmod +x /usr/local/bin/docker-compose

Note: Add your user to the docker group to run Docker without sudo:
   $ sudo usermod -aG docker $USER
   (Log out and log back in for changes to take effect)

After installation, restart your terminal and run this script again.
"""
    }
    
    guide = guides.get(os_name, """
Unable to provide specific installation instructions for your OS.
Please visit:
- Git: https://git-scm.com/downloads
- Docker: https://www.docker.com/get-started
""")
    
    print(guide)

# ============================================================================
# Repository Management
# ============================================================================
def clone_or_pull_repo(project_dir: Path) -> bool:
    """Clone the repository or pull latest changes if it exists."""
    print_section("Repository Setup")
    
    if project_dir.exists():
        print_info(f"Directory '{project_dir}' already exists")
        print_info("Pulling latest changes...")
        
        # Verify it's a git repository
        git_dir = project_dir / ".git"
        if not git_dir.exists():
            print_error(f"'{project_dir}' exists but is not a git repository")
            return False
        
        exit_code, stdout, stderr = run_command(
            ["git", "pull"],
            capture_output=False,
            check=False
        )
        
        if exit_code == 0:
            print_success("Repository updated successfully")
            return True
        else:
            print_error("Failed to pull latest changes")
            if stderr:
                print_warning(stderr)
            return False
    else:
        print_info(f"Cloning repository from {REPO_URL}...")
        exit_code, stdout, stderr = run_command(
            ["git", "clone", REPO_URL, str(project_dir)],
            capture_output=False,
            check=False
        )
        
        if exit_code == 0:
            print_success(f"Repository cloned to '{project_dir}'")
            return True
        else:
            print_error("Failed to clone repository")
            if stderr:
                print_warning(stderr)
            return False

# ============================================================================
# Directory & Permission Setup
# ============================================================================
def create_directories(project_dir: Path) -> bool:
    """Create required directories inside the project root."""
    print_section("Creating Required Directories")
    
    all_created = True
    for dir_path in REQUIRED_DIRS:
        full_path = project_dir / dir_path
        try:
            full_path.mkdir(parents=True, exist_ok=True)
            print_success(f"Created: {dir_path}")
        except Exception as e:
            print_error(f"Failed to create {dir_path}: {e}")
            all_created = False
    
    return all_created

def fix_permissions(project_dir: Path) -> bool:
    """Fix permissions for Docker bind mounts (Linux only)."""
    os_name = get_os()
    
    print_section("Setting Directory Permissions")
    print_info(f"Detected OS: {get_os_display_name()}")
    
    if os_name != "linux":
        print_info("Docker Desktop handles volume permissions automatically on this OS")
        print_success("Skipping permission changes")
        return True
    
    # Linux-specific permission fix
    print_warning("Linux detected: Setting ownership for Docker containers (UID 50000)")
    print_info("This requires sudo privileges for Airflow compatibility")
    
    dirs_to_chown = ["data", "output", "logs", "airflow"]
    chown_cmd = ["sudo", "chown", "-R", f"{AIRFLOW_UID}:{AIRFLOW_GID}"]
    
    for dir_name in dirs_to_chown:
        dir_path = project_dir / dir_name
        if dir_path.exists():
            cmd = chown_cmd + [str(dir_path)]
            print_info(f"Running: {' '.join(cmd)}")
            
            exit_code, stdout, stderr = run_command(cmd, capture_output=False, check=False)
            
            if exit_code == 0:
                print_success(f"Ownership set for {dir_name}")
            else:
                print_error(f"Failed to set ownership for {dir_name}")
                print_warning("You may need to manually run: sudo chown -R 50000:0 " + dir_name)
                return False
    
    print_success("Permissions configured for Docker containers")
    return True

# ============================================================================
# Environment File Setup
# ============================================================================
def create_env_file(project_dir: Path) -> bool:
    """Create default .env file if it doesn't exist."""
    print_section("Environment Configuration")
    
    env_file = project_dir / ".env"
    
    if env_file.exists():
        print_info(f".env file already exists at {env_file}")
        print_warning("Skipping .env creation to preserve existing configuration")
        return True
    
    try:
        with open(env_file, 'w') as f:
            f.write(DEFAULT_ENV_CONTENT)
        print_success(f"Created default .env file at {env_file}")
        return True
    except Exception as e:
        print_error(f"Failed to create .env file: {e}")
        return False

# ============================================================================
# Docker Build
# ============================================================================
def build_docker_images(project_dir: Path) -> bool:
    """Build Docker images using docker compose."""
    print_section("Building Docker Images")
    
    print_info("This may take several minutes depending on your system...")
    response = input(f"{Colors.YELLOW}Do you want to build Docker images now? (y/n): {Colors.RESET}").strip().lower()
    
    if response not in ['y', 'yes']:
        print_info("Skipping Docker build. You can build later with:")
        print(f"  cd {project_dir}")
        print("  docker compose --profile airflow build")
        return True
    
    print_info("Starting Docker build...")
    
    # Change to project directory for build
    original_cwd = os.getcwd()
    try:
        os.chdir(project_dir)
        exit_code, stdout, stderr = run_command(
            ["docker", "compose", "--profile", "airflow", "build"],
            capture_output=False,
            check=False
        )
        
        if exit_code == 0:
            print_success("Docker images built successfully!")
            return True
        else:
            print_error("Docker build failed")
            print_info("You can try building manually with:")
            print(f"  cd {project_dir}")
            print("  docker compose --profile airflow build")
            return False
    except Exception as e:
        print_error(f"Error during Docker build: {e}")
        return False
    finally:
        os.chdir(original_cwd)

# ============================================================================
# Main Setup Flow
# ============================================================================
def main():
    """Main entry point for the setup script."""
    print_banner()
    
    # Get current working directory
    cwd = Path.cwd()
    project_dir = cwd / PROJECT_DIR_NAME
    
    # Detect OS
    os_name = get_os()
    print_info(f"Running on: {get_os_display_name()}")
    print_info(f"Working directory: {cwd}")
    print()
    
    # Step 1: Check Prerequisites
    print_section("Prerequisites Check")
    
    checks_passed = True
    
    if not check_git():
        checks_passed = False
    
    if not check_docker():
        checks_passed = False
    
    if not check_docker_compose():
        checks_passed = False
    
    if not checks_passed:
        print_error("One or more prerequisites are missing")
        print_installation_guide(os_name)
        sys.exit(1)
    
    print_success("All prerequisites are satisfied!")
    
    # Step 2: Clone or Pull Repository
    if not clone_or_pull_repo(project_dir):
        print_error("Repository setup failed")
        sys.exit(1)
    
    # Step 3: Create Required Directories
    if not create_directories(project_dir):
        print_error("Directory creation failed")
        sys.exit(1)
    
    # Step 4: Fix Permissions (Linux only)
    if not fix_permissions(project_dir):
        print_warning("Permission setup had issues, but continuing...")
    
    # Step 5: Create Environment File
    if not create_env_file(project_dir):
        print_warning("Environment file creation failed, but continuing...")
    
    # Step 6: Docker Build (Optional)
    build_docker_images(project_dir)
    
    # Final Summary
    print_section("Setup Complete!")
    print(f"""
{Colors.GREEN}AFA setup completed successfully!{Colors.RESET}

Next steps:
  1. Review and customize the .env file if needed:
     {project_dir / '.env'}
  
  2. Start the services:
     cd {project_dir}
     docker compose --profile airflow up -d
  
  3. Access Airflow UI:
     http://localhost:8080
     (Default credentials: admin / admin)

For more information, see the README.md file.
""")

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print(f"\n\n{Colors.YELLOW}Setup interrupted by user.{Colors.RESET}")
        sys.exit(130)
    except Exception as e:
        print(f"\n{Colors.RED}Fatal error: {e}{Colors.RESET}")
        sys.exit(1)
