"""afa_lab — a self-contained toolkit for the standalone strategy notebooks.

Everything the notebooks in this folder need: HuggingFace ingestion, cleaning,
feature construction, six strategies, a target-weight backtester and the charts.

**This module deliberately does not import `portfolio_agent`.** The notebooks
are a standalone re-implementation of the strategies the framework ships, so
they can be run, read and modified without installing the platform — copy this
folder anywhere and it works. Where a design choice mirrors the framework's, the
comment says why the choice is right rather than citing the framework.

Generated by `build/assemble.py` from `build/blocks/*.py`. Edit the blocks.

Requires: pandas, numpy, pyarrow, matplotlib, huggingface_hub, torch.
"""

from __future__ import annotations

import math
import os
import warnings
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence, Tuple

import numpy as np
import pandas as pd

try:
    import torch
    import torch.nn as nn
    import torch.nn.functional as F
    TORCH_AVAILABLE = True
except ImportError:  # the two learned strategies need it; the other four do not
    TORCH_AVAILABLE = False

import matplotlib.pyplot as plt
import matplotlib.ticker as mticker


# --- Data: HuggingFace ingestion, cleaning, local cache -----------------------
# Self-contained. Nothing here imports the portfolio_agent package.


HF_DATASET_ID = "vishnun0027/indian-market-historical-ohlcv"
HF_REVISION: Optional[str] = None   # pin a commit sha for a reproducible run
STOCKS_DIR = "stocks"
INDICES_DIR = "indices"

CACHE_DIR = Path("data_cache")
OHLCV = ("open", "high", "low", "close", "volume")

# Dataset layout (2,471 files, ~283 MB): one parquet per symbol under
# stocks/ (2,421), indices/ (17), etfs/, commodities/, forex/, metadata/.
# Per-file schema: date, open, high, low, close, adj_close, volume,
# dividends, stock_splits, symbol.
#
# Downloading per symbol rather than snapshotting the repo is deliberate: a
# 30-name universe fetches 30 small files instead of 283 MB.


def hub_filename(symbol: str, asset_dir: str = STOCKS_DIR) -> str:
    """Path of a symbol's parquet inside the dataset repo.

    Index symbols (^NSEI) keep their caret and live under indices/; equities
    are stored bare, without the .NS suffix the exchange uses.
    """
    bare = str(symbol).strip().upper()
    if bare.endswith(".NS"):
        bare = bare[:-3]
    return f"{asset_dir}/{bare}.parquet"


def clean_ohlcv(raw: pd.DataFrame, adjust_prices: bool = True) -> pd.DataFrame:
    """Map one raw Hub parquet onto a canonical, analysis-ready OHLCV frame.

    Steps, each of which exists because skipping it produces a plausible-looking
    but wrong series:

    1. **Back-adjust by adj_close/close.** On a 1:10 split the raw close drops
       90% in a single print. Momentum reads that as a crash and ATR-derived
       stops blow out. Scaling all four price legs by the same per-row factor
       removes the discontinuity while leaving intraday relationships intact —
       a locked session (high == low) stays locked.
    2. **Coerce numerics.** A single object-dtype column silently poisons every
       rolling statistic computed from it.
    3. **Drop unparseable dates and missing closes** rather than forward-filling
       them, so a gap stays visible as a gap.
    4. **Drop duplicate dates**, keeping the last — re-exports occasionally
       carry a corrected duplicate of the same session.
    """
    if raw is None or len(raw) == 0:
        raise ValueError("empty frame")

    df = raw.copy()
    df.columns = [str(c).strip().lower().replace(" ", "_") for c in df.columns]

    if "date" not in df.columns:
        raise ValueError(f"no date column; got {list(df.columns)}")
    if "close" not in df.columns and "adj_close" not in df.columns:
        raise ValueError(f"no close column; got {list(df.columns)}")

    out = pd.DataFrame(index=pd.RangeIndex(len(df)))
    for column in ("open", "high", "low", "close", "adj_close", "volume"):
        if column in df.columns:
            out[column] = pd.to_numeric(df[column].to_numpy(), errors="coerce")

    if "close" not in out.columns:
        out["close"] = out["adj_close"]

    if adjust_prices and "adj_close" in out.columns:
        factor = (out["adj_close"] / out["close"]).replace([np.inf, -np.inf], np.nan).fillna(1.0)
        for leg in ("open", "high", "low", "close"):
            if leg in out.columns:
                out[leg] = out[leg] * factor

    out = out.drop(columns=[c for c in ("adj_close",) if c in out.columns])

    # A file carrying only a close is still usable for close-based signals;
    # a uniform column set matters more than the missing legs.
    for leg in ("open", "high", "low"):
        if leg not in out.columns:
            out[leg] = out["close"]
    # Volume defaults to 0, never to a fabricated number — a liquidity screen
    # reads it, and an invented volume defeats the screen entirely.
    if "volume" not in out.columns:
        out["volume"] = 0.0

    index = pd.to_datetime(df["date"].to_numpy(), errors="coerce", utc=True)
    out.index = pd.DatetimeIndex(index).tz_localize(None)
    out.index.name = "date"

    out = out[out.index.notna() & out["close"].notna()]
    if out.empty:
        raise ValueError("every row had an unparseable date or a missing close")

    out = out[~out.index.duplicated(keep="last")]
    return out[list(OHLCV)].sort_index()


def download_symbol(
    symbol: str,
    asset_dir: str = STOCKS_DIR,
    revision: Optional[str] = HF_REVISION,
    dataset_id: str = HF_DATASET_ID,
) -> Optional[pd.DataFrame]:
    """Fetch and clean one symbol. Returns None when the symbol is absent.

    A missing symbol is an ordinary outcome for a universe list that runs ahead
    of the dataset, not a reason to abort an ingest.
    """
    from huggingface_hub import hf_hub_download

    try:
        path = hf_hub_download(
            repo_id=dataset_id,
            filename=hub_filename(symbol, asset_dir),
            repo_type="dataset",
            revision=revision,
        )
    except Exception:
        return None

    try:
        return clean_ohlcv(pd.read_parquet(path))
    except Exception as exc:
        warnings.warn(f"{symbol}: {exc}")
        return None


def list_hub_symbols(
    asset_dir: str = STOCKS_DIR,
    revision: Optional[str] = HF_REVISION,
    dataset_id: str = HF_DATASET_ID,
) -> List[str]:
    """Every symbol available in one asset directory."""
    from huggingface_hub import HfApi

    files = HfApi().list_repo_files(dataset_id, repo_type="dataset", revision=revision)
    prefix = f"{asset_dir}/"
    return sorted(
        Path(name).stem for name in files
        if name.startswith(prefix) and name.endswith(".parquet")
    )


def _synthetic_panel(
    symbols: Sequence[str], n_days: int = 1500, seed: int = 7
) -> Dict[str, pd.DataFrame]:
    """Offline stand-in with realistic structure, for when the Hub is unreachable.

    Deliberately *not* a plain random walk: it carries a common market factor,
    per-name idiosyncratic drift, volatility clustering and occasional gaps, so
    a cross-sectional strategy has something to rank and a risk model has
    something to estimate. It is still synthetic — any number produced from it
    describes the generator, not the market. Never read a result off this.
    """
    rng = np.random.default_rng(seed)
    index = pd.date_range("2018-01-01", periods=n_days, freq="B")

    market = rng.normal(0.0003, 0.010, n_days)
    vol_state = np.abs(rng.normal(1.0, 0.35, n_days))
    vol_state = pd.Series(vol_state).ewm(span=40).mean().to_numpy()

    panel: Dict[str, pd.DataFrame] = {}
    for i, symbol in enumerate(symbols):
        beta = 0.5 + 1.2 * rng.random()
        drift = rng.normal(0.0002, 0.0004)
        idio = rng.normal(0.0, 0.011 + 0.006 * rng.random(), n_days)
        returns = drift + beta * market * vol_state + idio * vol_state

        close = 100.0 * np.exp(np.cumsum(returns)) * (0.5 + 2.5 * rng.random())
        intraday = np.abs(rng.normal(0.008, 0.004, n_days))
        frame = pd.DataFrame(
            {
                "open": close * (1 + rng.normal(0, 0.003, n_days)),
                "high": close * (1 + intraday),
                "low": close * (1 - intraday),
                "close": close,
                "volume": rng.lognormal(13.0 + 0.4 * rng.random(), 0.6, n_days),
            },
            index=index,
        )
        frame["high"] = frame[["high", "open", "close"]].max(axis=1)
        frame["low"] = frame[["low", "open", "close"]].min(axis=1)

        # A few missing sessions, so the cleaning path is actually exercised.
        drop = rng.choice(n_days, size=max(1, n_days // 200), replace=False)
        frame = frame.drop(frame.index[drop])

        panel[symbol] = frame
        _ = i
    return panel


def load_panel(
    symbols: Sequence[str],
    start_date: Optional[str] = None,
    end_date: Optional[str] = None,
    cache_dir: Path = CACHE_DIR,
    use_cache: bool = True,
    allow_synthetic: bool = True,
    revision: Optional[str] = HF_REVISION,
) -> Dict[str, pd.DataFrame]:
    """Load a cleaned OHLCV panel, downloading only what is not already cached.

    Falls back to a synthetic panel when the Hub cannot be reached, so the rest
    of a notebook still runs offline. The fallback is announced loudly, because
    a synthetic result that is mistaken for a real one is the worst outcome here.

    Returns:
        `{symbol: DataFrame}` for every symbol that yielded usable data.
    """
    cache_dir = Path(cache_dir)
    cache_dir.mkdir(parents=True, exist_ok=True)

    panel: Dict[str, pd.DataFrame] = {}
    missing: List[str] = []

    for symbol in symbols:
        path = cache_dir / f"{symbol.replace('^', '_')}.parquet"
        if use_cache and path.exists():
            panel[symbol] = pd.read_parquet(path)
        else:
            missing.append(symbol)

    if missing:
        try:
            for symbol in missing:
                asset_dir = INDICES_DIR if symbol.startswith("^") else STOCKS_DIR
                frame = download_symbol(symbol, asset_dir=asset_dir, revision=revision)
                if frame is None:
                    continue
                panel[symbol] = frame
                frame.to_parquet(cache_dir / f"{symbol.replace('^', '_')}.parquet")
        except Exception as exc:
            if not allow_synthetic:
                raise
            print("=" * 74)
            print("HuggingFace unreachable — falling back to SYNTHETIC data.")
            print(f"  reason: {type(exc).__name__}: {str(exc)[:160]}")
            print("  Every number below describes the generator, not the market.")
            print("  Install `huggingface_hub` and re-run with network access for real data.")
            print("=" * 74)
            panel = _synthetic_panel(list(symbols))

    if not panel and allow_synthetic:
        print("=" * 74)
        print("No symbols resolved — falling back to SYNTHETIC data. Results are not real.")
        print("=" * 74)
        panel = _synthetic_panel(list(symbols))

    if start_date or end_date:
        lo = pd.Timestamp(start_date) if start_date else None
        hi = pd.Timestamp(end_date) if end_date else None
        for symbol, frame in list(panel.items()):
            if lo is not None:
                frame = frame[frame.index >= lo]
            if hi is not None:
                frame = frame[frame.index <= hi]
            if frame.empty:
                panel.pop(symbol)
            else:
                panel[symbol] = frame

    return panel


def panel_quality(panel: Dict[str, pd.DataFrame]) -> pd.DataFrame:
    """Per-symbol data-quality summary — read this before trusting a backtest."""
    rows = []
    for symbol, frame in sorted(panel.items()):
        close = frame["close"]
        returns = close.pct_change()
        sessions = len(frame)
        expected = len(pd.date_range(frame.index.min(), frame.index.max(), freq="B"))
        rows.append({
            "symbol": symbol,
            "rows": sessions,
            "start": frame.index.min().date(),
            "end": frame.index.max().date(),
            "coverage": round(sessions / max(expected, 1), 3),
            "zero_vol_days": int((frame["volume"] <= 0).sum()),
            "flat_days": int((returns.abs() < 1e-9).sum()),
            "max_1d_move": round(float(returns.abs().max()), 4),
            "ann_vol": round(float(returns.std() * np.sqrt(252)), 4),
        })
    return pd.DataFrame(rows)


def align_close_matrix(panel: Dict[str, pd.DataFrame]) -> pd.DataFrame:
    """Wide close-price matrix (dates x symbols) on the union of trading days.

    Left as NaN where a symbol has no print. Forward-filling here would invent
    prices a backtest could trade on; the strategies below handle NaN by simply
    not ranking a name that has none.
    """
    return pd.DataFrame({s: f["close"] for s, f in panel.items()}).sort_index()


# --- Features: the indicator set the strategies below are defined on ----------


TRADING_DAYS = 252


def sma(close: pd.Series, window: int) -> pd.Series:
    return close.rolling(window, min_periods=window).mean()


def rsi(close: pd.Series, window: int = 14) -> pd.Series:
    """Wilder's RSI. Uses an EWM with alpha=1/window, which is Wilder smoothing."""
    delta = close.diff()
    gain = delta.clip(lower=0.0)
    loss = -delta.clip(upper=0.0)
    avg_gain = gain.ewm(alpha=1 / window, min_periods=window, adjust=False).mean()
    avg_loss = loss.ewm(alpha=1 / window, min_periods=window, adjust=False).mean()
    rs = avg_gain / avg_loss.replace(0.0, np.nan)
    return (100.0 - 100.0 / (1.0 + rs)).fillna(50.0)


def macd(close: pd.Series, fast: int = 12, slow: int = 26, signal: int = 9) -> pd.Series:
    """MACD histogram — the part that carries the signal, not the raw line."""
    ema_fast = close.ewm(span=fast, adjust=False).mean()
    ema_slow = close.ewm(span=slow, adjust=False).mean()
    line = ema_fast - ema_slow
    return line - line.ewm(span=signal, adjust=False).mean()


def bollinger_pct_b(close: pd.Series, window: int = 20, n_std: float = 2.0) -> pd.Series:
    """Position within the Bollinger band: 0 at the lower band, 1 at the upper."""
    mid = close.rolling(window, min_periods=window).mean()
    std = close.rolling(window, min_periods=window).std()
    width = (2 * n_std * std).replace(0.0, np.nan)
    return (close - (mid - n_std * std)) / width


def true_range(frame: pd.DataFrame) -> pd.Series:
    """True range, which unlike high-low accounts for the overnight gap.

    On Indian equities the gap is where a large share of the move happens —
    a circuit-limited open is entirely gap — so high-low alone understates
    realized range and every ATR-derived stop built on it is too tight.
    """
    prev_close = frame["close"].shift(1)
    return pd.concat(
        [
            frame["high"] - frame["low"],
            (frame["high"] - prev_close).abs(),
            (frame["low"] - prev_close).abs(),
        ],
        axis=1,
    ).max(axis=1)


def atr(frame: pd.DataFrame, window: int = 14) -> pd.Series:
    return true_range(frame).ewm(alpha=1 / window, min_periods=window, adjust=False).mean()


def realized_vol(close: pd.Series, window: int = 60) -> pd.Series:
    """Annualized realized volatility of daily log returns."""
    log_returns = np.log(close / close.shift(1))
    return log_returns.rolling(window, min_periods=window).std() * np.sqrt(TRADING_DAYS)


def momentum_skip(close: pd.Series, lookback: int = 252, skip: int = 21) -> pd.Series:
    """Total return over `lookback` sessions, excluding the most recent `skip`.

    The skip is not decoration. One-month returns reverse on average, so a
    momentum signal that includes the latest month is partly buying the very
    thing that is about to mean-revert; Jegadeesh-Titman skip the month for
    exactly this reason.
    """
    return close.shift(skip) / close.shift(lookback) - 1.0


def volume_ratio(volume: pd.Series, window: int = 20) -> pd.Series:
    """Today's volume against its trailing average — the confirmation term."""
    average = volume.rolling(window, min_periods=window).mean()
    return volume / average.replace(0.0, np.nan)


def traded_value(frame: pd.DataFrame, window: int = 60) -> pd.Series:
    """Average daily traded value: the liquidity measure that matters for sizing."""
    return (frame["close"] * frame["volume"]).rolling(window, min_periods=window).mean()


def rolling_high(close: pd.Series, window: int = 20) -> pd.Series:
    """Trailing high *excluding today*, so a breakout test is not self-referential."""
    return close.shift(1).rolling(window, min_periods=window).max()


def build_features(frame: pd.DataFrame) -> pd.DataFrame:
    """Every feature the strategies in these notebooks read, for one symbol.

    Returns a frame indexed like the input. Rows are left NaN until each
    window has filled — they are dropped where a strategy needs them, rather
    than back-filled, because a back-filled indicator is a look-ahead.
    """
    close, volume = frame["close"], frame["volume"]
    features = pd.DataFrame(index=frame.index)

    features["close"] = close
    features["return_1d"] = close.pct_change()
    features["return_5d"] = close.pct_change(5)
    features["return_21d"] = close.pct_change(21)

    features["sma_20"] = sma(close, 20)
    features["sma_50"] = sma(close, 50)
    features["sma_200"] = sma(close, 200)

    features["rsi_14"] = rsi(close, 14)
    features["macd"] = macd(close)
    features["bollinger_pct_b"] = bollinger_pct_b(close)
    features["atr_14"] = atr(frame, 14)
    features["atr_pct"] = features["atr_14"] / close

    features["realized_vol_60"] = realized_vol(close, 60)
    features["mom_9m_skip1m"] = momentum_skip(close, 189, 21)
    features["mom_12m_skip1m"] = momentum_skip(close, 252, 21)

    features["volume_ratio_20"] = volume_ratio(volume, 20)
    features["traded_value_60"] = traded_value(frame, 60)
    features["high_20"] = rolling_high(close, 20)
    features["breakout_20"] = close / features["high_20"] - 1.0

    return features


def build_feature_panel(panel: Dict[str, pd.DataFrame]) -> Dict[str, pd.DataFrame]:
    """Features for every symbol in a panel."""
    return {symbol: build_features(frame) for symbol, frame in panel.items()}


def cross_section(
    feature_panel: Dict[str, pd.DataFrame], column: str
) -> pd.DataFrame:
    """One feature as a wide dates x symbols matrix, for cross-sectional ranking."""
    return pd.DataFrame(
        {symbol: features[column] for symbol, features in feature_panel.items()}
    ).sort_index()


def zscore_rows(frame: pd.DataFrame) -> pd.DataFrame:
    """Standardize each date across symbols.

    Cross-sectional rather than time-series: the question a model choosing
    between stocks is asked is "is this high relative to what else I could buy
    today", not "is this high for this stock historically". It also strips the
    market factor out by construction, and cannot leak across dates since it
    fits no state.
    """
    mean = frame.mean(axis=1)
    std = frame.std(axis=1).replace(0.0, np.nan)
    return frame.sub(mean, axis=0).div(std, axis=0)


def rank_rows(frame: pd.DataFrame) -> pd.DataFrame:
    """Per-date cross-sectional rank scaled to [-1, 1].

    More robust than a z-score on Indian data, where a circuit-limited print
    dominates the cross-sectional mean but moves a ranking by one place.
    """
    ranked = frame.rank(axis=1, pct=True)
    return 2.0 * ranked - 1.0


# --- Backtest: target-weight portfolio simulation + performance statistics ----


TRADING_DAYS = 252


@dataclass
class BacktestConfig:
    """Simulation settings.

    Attributes:
        initial_capital: Starting equity, in INR.
        cost_bps: One-way cost in basis points, charged on traded notional.
            25 bps round-trip is a realistic all-in figure for Indian cash
            equities once brokerage, STT, exchange charges, GST, stamp duty and
            a modest slippage allowance are added up.
        max_weight: Cap on any single name's target weight.
        rebalance_days: Rebalance every N sessions. Daily rebalancing of a
            noisy signal spends most of its edge on costs; this is the main
            control over turnover.
        max_gross: Cap on total invested weight. 1.0 is long-only, unlevered.
        execution_lag: Sessions between a signal being observed and traded.
            Must be >= 1. Zero would let the simulation trade on a close it
            only knew after the fact — the single most common way a backtest
            manufactures a return that does not exist.
    """

    initial_capital: float = 1_000_000.0
    cost_bps: float = 25.0
    max_weight: float = 0.10
    rebalance_days: int = 5
    max_gross: float = 1.0
    execution_lag: int = 1

    def __post_init__(self) -> None:
        if self.execution_lag < 1:
            raise ValueError(
                "execution_lag must be at least 1 session: a signal computed from "
                "day t's close cannot be traded at day t's close"
            )
        if not 0 < self.max_weight <= 1.0:
            raise ValueError("max_weight must be in (0, 1]")


@dataclass
class BacktestResult:
    """Everything a run produced, ready to chart."""

    equity: pd.Series
    returns: pd.Series
    weights: pd.DataFrame
    turnover: pd.Series
    costs: pd.Series
    stats: Dict[str, float] = field(default_factory=dict)
    benchmark: Optional[pd.Series] = None

    @property
    def drawdown(self) -> pd.Series:
        peak = self.equity.cummax()
        return self.equity / peak - 1.0


def normalize_weights(
    raw: pd.DataFrame, config: BacktestConfig
) -> pd.DataFrame:
    """Turn arbitrary non-negative scores into tradeable target weights.

    Caps each name, renormalizes to `max_gross`, and leaves the remainder in
    cash rather than forcing full investment — a strategy that finds nothing
    worth holding should hold nothing, not the least-bad name available.
    """
    weights = raw.clip(lower=0.0).fillna(0.0)

    total = weights.sum(axis=1)
    scaled = weights.div(total.replace(0.0, np.nan), axis=0).fillna(0.0)
    scaled = scaled * config.max_gross

    # Capping frees up weight; one redistribution pass recovers most of it
    # without iterating to a fixed point, which is not worth the complexity
    # when the cap binds on a handful of names.
    #
    # Headroom is masked to names the strategy actually selected. Without that
    # mask the freed weight spreads across the *whole universe*, quietly turning
    # a concentrated signal into a near-index portfolio — a top-5 signal out of
    # 25 names came back holding 21 of them, with the extra 16 positions
    # contributed entirely by this line.
    selected = scaled > 0.0
    capped = scaled.clip(upper=config.max_weight)
    slack = (scaled.sum(axis=1) - capped.sum(axis=1)).clip(lower=0.0)
    headroom = (config.max_weight - capped).clip(lower=0.0).where(selected, 0.0)
    headroom_total = headroom.sum(axis=1).replace(0.0, np.nan)
    redistributed = capped + headroom.mul(slack / headroom_total, axis=0).fillna(0.0)

    return redistributed.clip(upper=config.max_weight).fillna(0.0)


def apply_rebalance_schedule(
    weights: pd.DataFrame, rebalance_days: int
) -> pd.DataFrame:
    """Hold targets between rebalance dates instead of re-trading every session."""
    if rebalance_days <= 1:
        return weights
    mask = pd.Series(False, index=weights.index)
    mask.iloc[::rebalance_days] = True
    held = weights.where(mask, other=np.nan)
    return held.ffill().fillna(0.0)


def run_backtest(
    target_weights: pd.DataFrame,
    close: pd.DataFrame,
    config: Optional[BacktestConfig] = None,
    benchmark: Optional[pd.Series] = None,
) -> BacktestResult:
    """Simulate a long-only target-weight portfolio.

    Args:
        target_weights: Desired weight per name per date, as computed from that
            date's close. Shifted forward by `execution_lag` internally, so the
            caller passes signals in signal-time and never has to remember to
            lag them.
        close: Close prices, same columns and index.
        config: Simulation settings.
        benchmark: Optional comparison series of returns.

    Returns:
        A `BacktestResult`.

    The accounting: weights drift with returns between rebalances (a name that
    doubled is a bigger share of the book), and turnover is measured against
    that *drifted* weight rather than the previous target. Measuring against the
    target overstates trading, because part of the move to the new target
    happened by itself.
    """
    config = config or BacktestConfig()

    close = close.sort_index()
    target_weights = target_weights.reindex(index=close.index, columns=close.columns).fillna(0.0)

    weights = normalize_weights(target_weights, config)
    weights = apply_rebalance_schedule(weights, config.rebalance_days)
    # The lag is applied after scheduling so a rebalance date means "the target
    # decided on this date", which is what a reader expects it to mean.
    weights = weights.shift(config.execution_lag).fillna(0.0)

    asset_returns = close.pct_change().replace([np.inf, -np.inf], np.nan).fillna(0.0)

    dates = close.index
    n_dates = len(dates)
    cost_rate = config.cost_bps / 10_000.0

    held = np.zeros(len(close.columns))
    equity = np.empty(n_dates)
    portfolio_returns = np.zeros(n_dates)
    turnover_series = np.zeros(n_dates)
    cost_series = np.zeros(n_dates)

    capital = config.initial_capital
    target_matrix = weights.to_numpy()
    return_matrix = asset_returns.to_numpy()

    for t in range(n_dates):
        target = target_matrix[t]

        traded = np.abs(target - held).sum()
        cost = traded * cost_rate
        held = target

        gross_return = float((held * return_matrix[t]).sum())
        net_return = gross_return - cost

        # Drift: a name that rose is now a larger share of the book. This is
        # what the next rebalance trades against.
        grown = held * (1.0 + return_matrix[t])
        total = grown.sum()
        if total > 0:
            held = grown * (held.sum() / total) if held.sum() > 0 else grown

        capital *= (1.0 + net_return)
        equity[t] = capital
        portfolio_returns[t] = net_return
        turnover_series[t] = traded
        cost_series[t] = cost

    equity_series = pd.Series(equity, index=dates, name="equity")
    returns_series = pd.Series(portfolio_returns, index=dates, name="return")

    result = BacktestResult(
        equity=equity_series,
        returns=returns_series,
        weights=weights,
        turnover=pd.Series(turnover_series, index=dates, name="turnover"),
        costs=pd.Series(cost_series, index=dates, name="cost"),
        benchmark=benchmark,
    )
    result.stats = performance_stats(returns_series, weights=weights,
                                     turnover=result.turnover)
    return result


def performance_stats(
    returns: pd.Series,
    weights: Optional[pd.DataFrame] = None,
    turnover: Optional[pd.Series] = None,
) -> Dict[str, float]:
    """Headline performance statistics for a daily return series.

    Sortino uses downside deviation about zero, and returns 0.0 rather than an
    infinity when a series has no losing day — an infinity wins every
    comparison it enters, which is exactly the wrong behaviour in a ranking.
    """
    returns = returns.dropna()
    if returns.empty:
        return {}

    n = len(returns)
    years = n / TRADING_DAYS
    total_return = float((1.0 + returns).prod() - 1.0)
    cagr = float((1.0 + total_return) ** (1 / years) - 1.0) if years > 0 and total_return > -1 else np.nan

    vol = float(returns.std(ddof=1) * np.sqrt(TRADING_DAYS)) if n > 1 else 0.0
    sharpe = float(returns.mean() / returns.std(ddof=1) * np.sqrt(TRADING_DAYS)) if n > 1 and returns.std(ddof=1) > 0 else 0.0

    downside = np.minimum(returns.to_numpy(), 0.0)
    downside_dev = float(np.sqrt(np.mean(downside ** 2)))
    sortino = float(returns.mean() / downside_dev * np.sqrt(TRADING_DAYS)) if downside_dev > 1e-12 else 0.0

    equity = (1.0 + returns).cumprod()
    max_drawdown = float((equity / equity.cummax() - 1.0).min())

    stats = {
        "total_return": total_return,
        "cagr": cagr,
        "ann_vol": vol,
        "sharpe": sharpe,
        "sortino": sortino,
        "max_drawdown": max_drawdown,
        "calmar": float(cagr / abs(max_drawdown)) if max_drawdown < -1e-9 and np.isfinite(cagr) else 0.0,
        "hit_rate": float((returns > 0).mean()),
        "best_day": float(returns.max()),
        "worst_day": float(returns.min()),
        "days": int(n),
    }

    if turnover is not None and len(turnover):
        stats["ann_turnover"] = float(turnover.sum() / max(years, 1e-9))
    if weights is not None and not weights.empty:
        gross = weights.sum(axis=1)
        stats["avg_exposure"] = float(gross.mean())
        stats["avg_positions"] = float((weights > 1e-6).sum(axis=1).mean())

    return stats


def equal_weight_benchmark(
    close: pd.DataFrame, config: Optional[BacktestConfig] = None
) -> BacktestResult:
    """Equal-weight buy-and-hold of the universe.

    The honest comparison for a long-only stock picker: beating cash is not the
    question, beating the same names held passively is.
    """
    config = config or BacktestConfig()
    available = close.notna().astype(float)
    weights = available.div(available.sum(axis=1).replace(0, np.nan), axis=0).fillna(0.0)
    # Buy and hold: one rebalance schedule so wide it never re-trades.
    passive = BacktestConfig(
        initial_capital=config.initial_capital,
        cost_bps=config.cost_bps,
        max_weight=1.0,
        rebalance_days=max(len(close), 1),
        max_gross=1.0,
        execution_lag=config.execution_lag,
    )
    return run_backtest(weights, close, passive)


def compare_stats(results: Dict[str, BacktestResult]) -> pd.DataFrame:
    """Side-by-side statistics table, best Sharpe first."""
    frame = pd.DataFrame({name: result.stats for name, result in results.items()}).T
    if "sharpe" in frame.columns:
        frame = frame.sort_values("sharpe", ascending=False)
    return frame.round(4)


# --- Strategies ---------------------------------------------------------------
# Each returns a dates x symbols matrix of non-negative target scores. The
# backtester normalizes, caps and lags them; no strategy here does its own
# position sizing, so they are all comparable on the same engine.


TRADING_DAYS = 252


def monte_carlo_win_probability(
    close: pd.Series,
    horizon: int = 21,
    n_paths: int = 400,
    lookback: int = 252,
    seed: int = 42,
) -> pd.Series:
    """Rolling probability that price is higher in `horizon` sessions.

    A block bootstrap over trailing log returns, not a Gaussian: Indian equity
    returns are fat-tailed and serially dependent enough that a normal
    approximation understates both tails, and the left one is the expensive
    side. Blocks of 5 preserve short-run autocorrelation.

    Computed on a coarse grid and forward-filled — running 400 paths on every
    session is the slowest thing in these notebooks and the estimate barely
    moves day to day.
    """
    rng = np.random.default_rng(seed)
    log_returns = np.log(close / close.shift(1)).dropna()
    probability = pd.Series(np.nan, index=close.index)

    block = 5
    n_blocks = max(1, horizon // block)
    step = 5

    positions = range(lookback, len(close), step)
    for i in positions:
        window = log_returns.iloc[max(0, i - lookback):i].to_numpy()
        if len(window) < block * 2:
            continue
        starts = rng.integers(0, len(window) - block, size=(n_paths, n_blocks))
        paths = np.stack([
            np.concatenate([window[s:s + block] for s in row]) for row in starts
        ])
        probability.iloc[i] = float((paths.sum(axis=1) > 0).mean())

    return probability.ffill()


# -- 1. Rule-based: trend + breakout + volume + Monte Carlo --------------------


@dataclass
class RuleBasedParams:
    """Weights and gates for the composite rule-based score."""

    trend_weight: float = 0.30
    breakout_weight: float = 0.25
    volume_weight: float = 0.20
    mc_weight: float = 0.25
    min_score: float = 0.55          # composite required to hold a name
    min_win_probability: float = 0.50
    require_trend: bool = True       # close > sma_200 is a hard gate, not a score


def rule_based_scores(
    feature_panel: Dict[str, pd.DataFrame],
    panel: Dict[str, pd.DataFrame],
    params: Optional[RuleBasedParams] = None,
    use_monte_carlo: bool = True,
) -> pd.DataFrame:
    """Composite of four components, each mapped to [0, 1] before weighting.

    Mapping every component onto a common scale before combining is what makes
    the weights mean what they say. Combining raw components — an RSI in
    [0,100] with a breakout in [-0.2, 0.2] — lets whichever has the widest
    natural range dominate regardless of its weight.
    """
    params = params or RuleBasedParams()
    scores: Dict[str, pd.Series] = {}

    for symbol, features in feature_panel.items():
        close = features["close"]

        # Trend: distance above the 200-day average, saturating at +20%.
        trend_raw = (close / features["sma_200"] - 1.0).clip(-0.2, 0.2)
        trend = (trend_raw + 0.2) / 0.4

        # Breakout: position against the trailing 20-day high (excluding today).
        breakout = (features["breakout_20"].clip(-0.1, 0.05) + 0.1) / 0.15

        # Volume confirmation: today's volume against its 20-day average.
        volume = (features["volume_ratio_20"].clip(0.5, 2.5) - 0.5) / 2.0

        if use_monte_carlo:
            win_probability = monte_carlo_win_probability(close)
        else:
            win_probability = pd.Series(0.5, index=close.index)
        mc = win_probability.clip(0.3, 0.7).sub(0.3).div(0.4)

        composite = (
            params.trend_weight * trend
            + params.breakout_weight * breakout
            + params.volume_weight * volume
            + params.mc_weight * mc
        )

        gate = composite >= params.min_score
        if params.require_trend:
            gate &= close > features["sma_200"]
        if use_monte_carlo:
            gate &= win_probability >= params.min_win_probability

        scores[symbol] = composite.where(gate, 0.0).fillna(0.0)

    return pd.DataFrame(scores).sort_index()


# -- 2. Cross-sectional momentum ----------------------------------------------


def momentum_scores(
    feature_panel: Dict[str, pd.DataFrame],
    top_fraction: float = 0.25,
    crash_filter: bool = True,
    vol_target: float = 0.25,
    min_traded_value: float = 0.0,
) -> pd.DataFrame:
    """Rank on 9-month momentum skipping the last month; hold the top slice.

    The crash filter is the part that earns its keep. Momentum's characteristic
    failure is not gradual underperformance but a crash: it loses most in the
    rebound *after* a drawdown, when the beaten-down names it is short (or
    simply not long) rally hardest. The state that predicts it is observable —
    market below its own 200-day average *and* realized volatility elevated —
    so the strategy stands down there rather than sizing through it.
    """
    from_column = lambda name: pd.DataFrame(
        {s: f[name] for s, f in feature_panel.items()}
    ).sort_index()

    momentum = from_column("mom_9m_skip1m")
    close = from_column("close")

    ranked = momentum.rank(axis=1, pct=True)
    selected = (ranked >= 1.0 - top_fraction).astype(float)

    if min_traded_value > 0:
        liquid = from_column("traded_value_60") >= min_traded_value
        selected = selected.where(liquid, 0.0)

    if crash_filter:
        # Equal-weight universe as the market proxy, so no index file is needed.
        market = close.mean(axis=1)
        market_trend = market > market.rolling(200, min_periods=200).mean()
        market_vol = np.log(market / market.shift(1)).rolling(60, min_periods=60).std() * np.sqrt(TRADING_DAYS)
        risk_on = market_trend & (market_vol <= 1.5 * vol_target)
        selected = selected.where(risk_on.reindex(selected.index).fillna(False), 0.0)

    # Score by rank within the selection, so the strongest names get more weight
    # than the marginal ones that just cleared the cut.
    return (selected * ranked).fillna(0.0)


# -- 3. Cross-sectional low volatility ----------------------------------------


TRADING_DAYS_PER_YEAR = 252


def idiosyncratic_volatility(
    close: pd.DataFrame, window: int = 60, lag: int = 1
) -> pd.DataFrame:
    """Volatility of the CAPM residual, per symbol, per date.

    **The residual, not the total**, and the distinction is the whole point of
    the sort. Total volatility mixes two things a cross-sectional book should
    keep apart: how much a stock moves *with* the market, and how much it moves
    on its own. Ranking on the sum puts high-beta names and
    idiosyncratically-wild names in the same bucket, and the 2025 work on the
    low-risk anomaly finds those two sorts behave very differently out of
    sample — idiosyncratic-volatility sorts survive where beta sorts largely do
    not.

    No regression loop is needed. For an OLS fit on a window,

        var(residual) = var(r_i) - beta^2 * var(r_m),  beta = cov(r_i, r_m) / var(r_m)

    and every term on the right is a `rolling` operation. Causality comes from
    `rolling` rather than being argued about: a window ends at the row it
    labels.

    The market is the equal-weighted composite of the cross-section itself,
    which is what this file has available and what the package falls back to.
    """
    returns = (close.shift(lag) if lag else close).pct_change()
    market = returns.mean(axis=1)

    floor = max(2, window // 2)
    market_var = market.rolling(window, min_periods=floor).var()
    safe_var = market_var.replace(0.0, np.nan)

    residual = {}
    for symbol in returns.columns:
        series = returns[symbol]
        own_var = series.rolling(window, min_periods=floor).var()
        covariance = series.rolling(window, min_periods=floor).cov(market)
        beta = covariance / safe_var
        variance = own_var - beta.pow(2) * market_var
        # Where the market was flat it explains nothing, so the residual is the
        # whole return rather than an undefined quantity.
        variance = variance.where(market_var.notna() & (market_var > 0), own_var)
        residual[symbol] = np.sqrt(variance.clip(lower=0.0))

    return pd.DataFrame(residual, index=returns.index) * np.sqrt(TRADING_DAYS_PER_YEAR)


def low_volatility_scores(
    feature_panel: Dict[str, pd.DataFrame],
    close: Optional[pd.DataFrame] = None,
    top_fraction: float = 0.25,
    min_history_vol: float = 1e-6,
    sort_on: str = "idiosyncratic",
) -> pd.DataFrame:
    """Hold the least volatile quartile, weighted by inverse volatility.

    The low-volatility anomaly is one of the most replicated results in equities
    and among the few that survive transaction costs at this turnover. Weighting
    by inverse vol rather than equally pushes the portfolio further along the
    same axis the selection is made on.

    `sort_on` defaults to `"idiosyncratic"` — the CAPM residual — matching the
    package since T14. `"total"` reproduces the original realized-volatility
    sort, which is worth keeping precisely so the two can be compared: they
    select different names, and the comparison is the finding.

    Args:
        feature_panel: Per-symbol feature frames. `realized_vol_60` is read for
            the total sort.
        close: Wide `(date x symbol)` closes. Required for the idiosyncratic
            sort, which needs the cross-section to residualize against.
        top_fraction: Quartile by default.
        min_history_vol: Floor before inverting, so a near-zero vol does not
            produce an unbounded weight.
        sort_on: `"idiosyncratic"` or `"total"`.

    Raises:
        ValueError: On an unknown `sort_on`, or the idiosyncratic sort without
            `close`. Falling back to the total sort would report one measure
            under the other's name.
    """
    if sort_on not in ("idiosyncratic", "total"):
        raise ValueError(
            f"sort_on must be 'idiosyncratic' or 'total', got {sort_on!r}"
        )

    if sort_on == "idiosyncratic":
        if close is None:
            raise ValueError(
                "the idiosyncratic sort needs `close` — a residual is defined "
                "against a cross-section. Falling back to the total sort would "
                "report one measure under the other's name."
            )
        vol = idiosyncratic_volatility(close).sort_index()
    else:
        vol = pd.DataFrame(
            {s: f["realized_vol_60"] for s, f in feature_panel.items()}
        ).sort_index()

    ranked = vol.rank(axis=1, pct=True)
    selected = (ranked <= top_fraction).astype(float)

    inverse_vol = 1.0 / vol.clip(lower=min_history_vol)
    return (selected * inverse_vol).replace([np.inf, -np.inf], 0.0).fillna(0.0)


# -- 6. Ensemble ---------------------------------------------------------------


def ensemble_scores(
    members: Dict[str, pd.DataFrame],
    weights: Optional[Dict[str, float]] = None,
    normalize_members: bool = True,
) -> pd.DataFrame:
    """Weighted blend of member score matrices.

    Members are put on a common scale first, per date. Without that, a member
    whose scores happen to be large (inverse volatility runs to tens) drowns one
    whose scores are bounded in [0, 1], and the configured weights describe
    something other than what the blend actually does.
    """
    if not members:
        raise ValueError("ensemble needs at least one member")

    weights = weights or {name: 1.0 / len(members) for name in members}
    missing = set(members) - set(weights)
    if missing:
        raise ValueError(f"no weight given for member(s): {sorted(missing)}")

    index = sorted(set().union(*[m.index for m in members.values()]))
    columns = sorted(set().union(*[m.columns for m in members.values()]))

    total = pd.DataFrame(0.0, index=pd.Index(index), columns=columns)
    for name, matrix in members.items():
        aligned = matrix.reindex(index=index, columns=columns).fillna(0.0)
        if normalize_members:
            row_max = aligned.max(axis=1).replace(0.0, np.nan)
            aligned = aligned.div(row_max, axis=0).fillna(0.0)
        total += weights[name] * aligned

    return total


def regime_gate(
    scores: pd.DataFrame,
    close: pd.DataFrame,
    trend_window: int = 200,
) -> pd.DataFrame:
    """Mute every score when the market proxy is below its long-run average.

    A blunt instrument, and deliberately so: it is the one regime signal that
    is observable in real time without estimating anything.
    """
    market = close.mean(axis=1)
    risk_on = market > market.rolling(trend_window, min_periods=trend_window).mean()
    return scores.where(risk_on.reindex(scores.index).fillna(False), 0.0)


# --- Learned models: supervised LSTM and a SAC allocation policy --------------


TRADING_DAYS = 252

MODEL_FEATURES = [
    "return_1d", "return_5d", "return_21d", "rsi_14", "macd",
    "bollinger_pct_b", "atr_pct", "realized_vol_60", "mom_9m_skip1m",
    "volume_ratio_20", "breakout_20",
]


def resolve_device(preference: str = "auto") -> torch.device:
    """Pick a device that actually exists, downgrading rather than failing."""
    if preference == "auto":
        if torch.cuda.is_available():
            return torch.device("cuda")
        if getattr(torch.backends, "mps", None) and torch.backends.mps.is_available():
            return torch.device("mps")
        return torch.device("cpu")
    if preference == "cuda" and not torch.cuda.is_available():
        print("CUDA requested but unavailable — using CPU.")
        return torch.device("cpu")
    return torch.device(preference)


def seed_everything(seed: int = 42) -> None:
    """Seed every generator these notebooks draw from.

    Without this a re-run gives different weights, and two 'comparable' runs
    differ by an amount nobody can separate from the change being tested.
    """
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


# =============================================================================
# Shared: the supervised panel
# =============================================================================


@dataclass
class Standardizer:
    """Per-feature mean/std fitted on training rows only.

    Fitting on the whole history leaks the test period's moments into the
    transform. The leak is small and entirely invisible in the resulting
    metrics, which is what makes it worth being strict about.
    """

    mean: np.ndarray
    std: np.ndarray
    clip: float = 10.0

    @classmethod
    def fit(cls, block: np.ndarray, clip: float = 10.0) -> "Standardizer":
        finite = np.where(np.isfinite(block), block, np.nan)
        mean = np.nanmean(finite, axis=0)
        std = np.nanstd(finite, axis=0)
        std = np.where(np.isfinite(std) & (std > 1e-8), std, 1.0)
        return cls(mean=np.nan_to_num(mean), std=std, clip=clip)

    def transform(self, block: np.ndarray) -> np.ndarray:
        scaled = (block - self.mean) / self.std
        scaled = np.nan_to_num(scaled, nan=0.0, posinf=self.clip, neginf=-self.clip)
        return np.clip(scaled, -self.clip, self.clip).astype(np.float32)

    def to_dict(self) -> Dict[str, object]:
        return {"mean": self.mean.tolist(), "std": self.std.tolist(), "clip": self.clip}


def cross_sectional_rank_target(
    close: pd.DataFrame, horizon: int = 5
) -> pd.DataFrame:
    """Forward return measured as a cross-sectional rank in [-1, 1].

    Predicting the *absolute* forward return spends the model's capacity on the
    market factor, which is nearly unforecastable and — for a long-only book
    with no index hedge — unusable even when forecast correctly. Ranking each
    name against the rest of the universe on the same date leaves the
    idiosyncratic part, which is what choosing between stocks can monetize.
    """
    forward = close.shift(-horizon) / close - 1.0
    ranked = forward.rank(axis=1, pct=True)
    return (2.0 * ranked - 1.0).where(forward.notna())


def build_supervised_panel(
    feature_panel: Dict[str, pd.DataFrame],
    close: pd.DataFrame,
    sequence_length: int = 30,
    horizon: int = 5,
    train_fraction: float = 0.7,
    val_fraction: float = 0.15,
    features: Sequence[str] = tuple(MODEL_FEATURES),
    max_abs_target: float = 1.0,
) -> Dict[str, object]:
    """Windowed sequences, split chronologically across the whole panel.

    The split is by *date*, not by row: every symbol's training window ends
    before any symbol's validation window begins. Splitting by row after
    stacking symbols would put one name's future alongside another's past.
    """
    features = list(features)
    target = cross_sectional_rank_target(close, horizon)

    dates = close.index
    train_end = dates[int(len(dates) * train_fraction)]
    val_end = dates[int(len(dates) * (train_fraction + val_fraction))]

    windows: Dict[str, List[np.ndarray]] = {"train": [], "val": [], "test": []}
    labels: Dict[str, List[float]] = {"train": [], "val": [], "test": []}
    keys: Dict[str, List[Tuple[pd.Timestamp, str]]] = {"train": [], "val": [], "test": []}

    for symbol, frame in feature_panel.items():
        if symbol not in target.columns:
            continue
        block = frame.reindex(columns=features)
        y = target[symbol].reindex(block.index)

        usable = block.notna().all(axis=1) & y.notna() & (y.abs() <= max_abs_target)
        values = block.to_numpy(dtype=np.float64)
        y_values = y.to_numpy(dtype=np.float64)
        usable_values = usable.to_numpy()

        for end in range(sequence_length, len(block)):
            if not usable_values[end]:
                continue
            window = values[end - sequence_length:end]
            if not np.isfinite(window).all():
                continue
            date = block.index[end]
            split = "train" if date <= train_end else ("val" if date <= val_end else "test")
            windows[split].append(window)
            labels[split].append(y_values[end])
            keys[split].append((date, symbol))

    if not windows["train"]:
        raise ValueError(
            "no training windows — the panel is too short for "
            f"sequence_length={sequence_length} plus horizon={horizon}"
        )

    train_block = np.concatenate([w for w in windows["train"]], axis=0)
    standardizer = Standardizer.fit(train_block)

    out: Dict[str, object] = {
        "features": features,
        "standardizer": standardizer,
        "sequence_length": sequence_length,
        "horizon": horizon,
        "train_end": train_end,
        "val_end": val_end,
    }
    for split in ("train", "val", "test"):
        if windows[split]:
            stacked = np.stack(windows[split])
            shape = stacked.shape
            scaled = standardizer.transform(stacked.reshape(-1, shape[-1])).reshape(shape)
        else:
            scaled = np.zeros((0, sequence_length, len(features)), dtype=np.float32)
        out[f"X_{split}"] = scaled
        out[f"y_{split}"] = np.asarray(labels[split], dtype=np.float32)
        out[f"keys_{split}"] = keys[split]

    return out


# =============================================================================
# LSTM forecaster
# =============================================================================


class LSTMForecaster(nn.Module):
    """Two-layer LSTM over a feature window, predicting a cross-sectional rank."""

    def __init__(self, n_features: int, hidden_size: int = 64,
                 n_layers: int = 2, dropout: float = 0.2):
        super().__init__()
        self.lstm = nn.LSTM(
            input_size=n_features, hidden_size=hidden_size, num_layers=n_layers,
            batch_first=True, dropout=dropout if n_layers > 1 else 0.0,
        )
        self.head = nn.Sequential(
            nn.Dropout(dropout),
            nn.Linear(hidden_size, 32),
            nn.ReLU(),
            nn.Linear(32, 1),
            # The label is a rank in [-1, 1]; bounding the output to match keeps
            # the loss from being dominated by predictions outside the target's
            # own range, which carry no information.
            nn.Tanh(),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        output, _ = self.lstm(x)
        return self.head(output[:, -1, :]).squeeze(-1)


def train_lstm(
    panel: Dict[str, object],
    epochs: int = 30,
    batch_size: int = 256,
    learning_rate: float = 1e-3,
    hidden_size: int = 64,
    patience: int = 6,
    device: str = "auto",
    seed: int = 42,
    verbose: bool = True,
) -> Dict[str, object]:
    """Fit the forecaster, selecting the epoch with the best validation loss.

    Early stopping is on validation loss, and the returned weights are the best
    epoch's rather than the last — on this signal-to-noise ratio a model
    reliably keeps improving in-sample long after it has stopped generalizing.
    """
    seed_everything(seed)
    torch_device = resolve_device(device)

    X_train = torch.tensor(panel["X_train"])
    y_train = torch.tensor(panel["y_train"])
    X_val = torch.tensor(panel["X_val"]).to(torch_device)
    y_val = torch.tensor(panel["y_val"]).to(torch_device)

    model = LSTMForecaster(X_train.shape[-1], hidden_size=hidden_size).to(torch_device)
    optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, patience=3, factor=0.5)

    dataset = torch.utils.data.TensorDataset(X_train, y_train)
    generator = torch.Generator().manual_seed(seed)
    loader = torch.utils.data.DataLoader(
        dataset, batch_size=batch_size, shuffle=True, generator=generator
    )

    history: List[Dict[str, float]] = []
    best_val, best_state, best_epoch, stale = math.inf, None, 0, 0

    for epoch in range(1, epochs + 1):
        model.train()
        total, seen = 0.0, 0
        for xb, yb in loader:
            xb, yb = xb.to(torch_device), yb.to(torch_device)
            optimizer.zero_grad(set_to_none=True)
            loss = F.mse_loss(model(xb), yb)
            loss.backward()
            nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()
            total += float(loss.item()) * len(xb)
            seen += len(xb)

        model.eval()
        with torch.no_grad():
            val_pred = model(X_val) if len(X_val) else torch.zeros(0, device=torch_device)
            val_loss = float(F.mse_loss(val_pred, y_val).item()) if len(X_val) else math.nan
            ic = (
                _rank_ic(val_pred, y_val, _dates_of(panel.get("keys_val")))
                if len(X_val) > 2 else math.nan
            )

        scheduler.step(val_loss if math.isfinite(val_loss) else 0.0)
        history.append({
            "epoch": epoch,
            "train_loss": total / max(seen, 1),
            "val_loss": val_loss,
            "val_rank_ic": ic,
        })

        if verbose and (epoch == 1 or epoch % 5 == 0):
            print(f"  epoch {epoch:3d}  train {total/max(seen,1):.5f}  "
                  f"val {val_loss:.5f}  rank-IC {ic:+.4f}")

        if math.isfinite(val_loss) and val_loss < best_val - 1e-6:
            best_val, best_epoch, stale = val_loss, epoch, 0
            best_state = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
        else:
            stale += 1
            if stale >= patience:
                if verbose:
                    print(f"  early stop at epoch {epoch} (best was {best_epoch})")
                break

    if best_state is not None:
        model.load_state_dict(best_state)
    model.eval()

    return {
        "model": model,
        "device": torch_device,
        "history": pd.DataFrame(history),
        "best_epoch": best_epoch,
        "best_val_loss": best_val,
        "standardizer": panel["standardizer"],
        "features": panel["features"],
        "sequence_length": panel["sequence_length"],
    }


def _dates_of(keys: Optional[Sequence]) -> Optional[List]:
    """The date half of a panel's `(date, symbol)` keys."""
    return None if not keys else [key[0] for key in keys]


#: Names below which a date's cross-section is too thin to rank. Matches
#: `evaluation/metrics.MIN_CROSS_SECTION_NAMES` in the package.
MIN_CROSS_SECTION_NAMES = 5


def _rank_ic(
    predictions: torch.Tensor,
    targets: torch.Tensor,
    dates: Optional[Sequence] = None,
) -> float:
    """Mean per-date Spearman correlation — the metric the ranking is used as.

    **Per date, not pooled**, and the difference is not a detail. Pooling every
    validation observation into one rank correlation measures whether the score
    tracks the market's *level* over time; the model is used to order *one
    day's* cross-section, and those are different questions with different
    answers. On a signal that orders every date perfectly while its level runs
    against the market, the pooled figure is -0.99 and the per-date figure is
    +1.00.

    The package carried the pooled version until T12, where it was driving
    model selection with the wrong sign. This file kept it afterwards, which is
    the drift `test_standalone_agrees.py` now exists to catch.

    Args:
        predictions, targets: Aligned validation tensors.
        dates: The decision date of each observation, from the panel's
            `keys_val`. **Required in practice**: without it there is no
            cross-section to correlate within, so the function refuses rather
            than silently pooling.

    Returns:
        Mean of the per-date correlations, or NaN when no date had a wide
        enough cross-section.
    """
    p = predictions.detach().cpu().numpy().ravel()
    t = targets.detach().cpu().numpy().ravel()
    if len(p) < 3:
        return float("nan")

    if dates is None:
        # Refusing rather than pooling. A pooled number here is not a worse
        # estimate of the same quantity — it is an estimate of a different one.
        return float("nan")

    frame = pd.DataFrame({"date": list(dates), "score": p, "label": t})
    per_date: List[float] = []
    for _date, group in frame.groupby("date", sort=True):
        if len(group) < MIN_CROSS_SECTION_NAMES:
            continue
        sr = group["score"].rank().to_numpy()
        lr = group["label"].rank().to_numpy()
        if sr.std() < 1e-12 or lr.std() < 1e-12:
            continue
        per_date.append(float(np.corrcoef(sr, lr)[0, 1]))

    return float(np.mean(per_date)) if per_date else float("nan")


def lstm_scores(
    trained: Dict[str, object],
    feature_panel: Dict[str, pd.DataFrame],
    close: pd.DataFrame,
    top_fraction: float = 0.25,
    batch_size: int = 1024,
) -> pd.DataFrame:
    """Score every (date, symbol) and keep the top slice per date.

    Predictions are produced for all dates including the training period, so the
    equity curve can be split into in-sample and out-of-sample segments. Only
    the segment after `panel["val_end"]` is evidence of anything.
    """
    model = trained["model"]
    device = trained["device"]
    standardizer: Standardizer = trained["standardizer"]
    features = list(trained["features"])
    sequence_length = int(trained["sequence_length"])

    predictions = pd.DataFrame(np.nan, index=close.index, columns=close.columns)

    model.eval()
    for symbol, frame in feature_panel.items():
        if symbol not in close.columns:
            continue
        block = frame.reindex(columns=features)
        values = block.to_numpy(dtype=np.float64)
        valid = np.isfinite(values).all(axis=1)

        windows, dates = [], []
        for end in range(sequence_length, len(block)):
            if not valid[end - sequence_length:end].all():
                continue
            windows.append(values[end - sequence_length:end])
            dates.append(block.index[end])

        if not windows:
            continue

        stacked = np.stack(windows)
        shape = stacked.shape
        scaled = standardizer.transform(stacked.reshape(-1, shape[-1])).reshape(shape)

        outputs: List[np.ndarray] = []
        with torch.no_grad():
            for start in range(0, len(scaled), batch_size):
                chunk = torch.tensor(scaled[start:start + batch_size]).to(device)
                outputs.append(model(chunk).cpu().numpy())

        predictions.loc[dates, symbol] = np.concatenate(outputs)

    ranked = predictions.rank(axis=1, pct=True)
    selected = (ranked >= 1.0 - top_fraction).astype(float)
    return (selected * ranked).fillna(0.0)


# =============================================================================
# SAC allocation policy
# =============================================================================


class SACActor(nn.Module):
    """Squashed-Gaussian policy mapping a feature vector to a weight in [0, 1].

    Sigmoid rather than tanh because the book is long-only and unlevered, so
    there is nothing for a negative half to mean. Inference uses the mean
    action, not a sample: sampling would make two runs of one backtest disagree.
    """

    def __init__(self, state_dim: int, hidden_dim: int = 128):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(state_dim, hidden_dim), nn.ReLU(),
            nn.Linear(hidden_dim, hidden_dim), nn.ReLU(),
        )
        self.mean_head = nn.Linear(hidden_dim, 1)
        self.log_std_head = nn.Linear(hidden_dim, 1)

    def forward(self, state: torch.Tensor) -> torch.Tensor:
        return torch.sigmoid(self.mean_head(self.net(state)))

    def sample(self, state: torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor]:
        hidden = self.net(state)
        mean = self.mean_head(hidden)
        log_std = torch.clamp(self.log_std_head(hidden), -5.0, 2.0)
        std = log_std.exp()

        normal = torch.distributions.Normal(mean, std)
        pre_squash = normal.rsample()
        action = torch.sigmoid(pre_squash)
        # The sigmoid's Jacobian correction. Omitting it silently changes the
        # entropy target and the temperature the tuner settles on.
        log_prob = normal.log_prob(pre_squash) - torch.log(action * (1 - action) + 1e-6)
        return action, log_prob


class TwinCritic(nn.Module):
    """Two Q networks; the min of the pair is SAC's overestimation defence."""

    def __init__(self, state_dim: int, hidden_dim: int = 128):
        super().__init__()
        build = lambda: nn.Sequential(
            nn.Linear(state_dim + 1, hidden_dim), nn.ReLU(),
            nn.Linear(hidden_dim, hidden_dim), nn.ReLU(),
            nn.Linear(hidden_dim, 1),
        )
        self.q1, self.q2 = build(), build()

    def forward(self, state, action):
        joint = torch.cat([state, action], dim=-1)
        return self.q1(joint), self.q2(joint)


class DifferentialSortino:
    """Online Sortino whose per-step increment is the reward.

    Moody & Saffell's differential Sharpe with the second moment replaced by the
    downside second moment. Summing the increments approximates the Sortino
    ratio of the whole path, so maximizing per-step reward maximizes a
    downside-aware ratio — the distinction that stops the policy learning
    "hold maximum size always".
    """

    def __init__(self, eta: float = 0.02, clip: float = 10.0):
        self.eta, self.clip = eta, clip
        self.a, self.dd2 = 0.0, 0.0

    def warmup(self, r: float) -> None:
        self.a += self.eta * (r - self.a)
        self.dd2 += self.eta * (min(r, 0.0) ** 2 - self.dd2)

    def update(self, r: float) -> float:
        delta_a = r - self.a
        delta_dd2 = min(r, 0.0) ** 2 - self.dd2
        if self.dd2 > 1e-12:
            reward = (self.dd2 * delta_a - 0.5 * self.a * delta_dd2) / (self.dd2 ** 1.5)
        else:
            reward = delta_a
        self.a += self.eta * delta_a
        self.dd2 += self.eta * delta_dd2
        if not math.isfinite(reward):
            return 0.0
        return float(np.clip(reward, -self.clip, self.clip))


@dataclass
class ReplayBuffer:
    """Fixed-capacity transition store with its own seeded generator.

    Its own generator, not the global numpy state: otherwise a run depends on
    every other caller that happened to draw a random number.
    """

    capacity: int
    state_dim: int
    seed: int = 42

    def __post_init__(self):
        self.states = np.zeros((self.capacity, self.state_dim), dtype=np.float32)
        self.actions = np.zeros((self.capacity, 1), dtype=np.float32)
        self.rewards = np.zeros((self.capacity, 1), dtype=np.float32)
        self.next_states = np.zeros((self.capacity, self.state_dim), dtype=np.float32)
        self._size, self._pos = 0, 0
        self._rng = np.random.default_rng(self.seed)

    def __len__(self) -> int:
        return self._size

    def push(self, state, action, reward, next_state) -> None:
        i = self._pos
        self.states[i], self.actions[i] = state, action
        self.rewards[i], self.next_states[i] = reward, next_state
        self._pos = (self._pos + 1) % self.capacity
        self._size = min(self._size + 1, self.capacity)

    def sample(self, batch_size: int):
        if self._size == 0:
            raise ValueError("empty replay buffer")
        idx = self._rng.integers(0, self._size, size=batch_size)
        return (self.states[idx], self.actions[idx],
                self.rewards[idx], self.next_states[idx])


def train_sac(
    feature_panel: Dict[str, pd.DataFrame],
    close: pd.DataFrame,
    features: Sequence[str] = tuple(MODEL_FEATURES),
    epochs: int = 40,
    batch_size: int = 256,
    learning_rate: float = 3e-4,
    hidden_dim: int = 128,
    gamma: float = 0.0,
    tau: float = 0.005,
    friction_cost: float = 0.008,
    train_fraction: float = 0.7,
    gradient_steps: int = 150,
    buffer_size: int = 200_000,
    device: str = "auto",
    seed: int = 42,
    verbose: bool = True,
) -> Dict[str, object]:
    """Train a per-name allocation policy with twin-critic SAC.

    `gamma` defaults to 0 on purpose. Discounting assumes the action influences
    the next state; a price-taking book does not move the market, so the state
    sequence is exogenous and bootstrapping over it adds estimator variance
    without adding signal. With gamma=0 the critic learns Q(s,a) = E[r|s,a] and
    the actor maximizes Q - alpha*log pi — soft actor-critic on what this
    decision actually is, a contextual bandit.

    The reward is the differential Sortino of `a_t * ret_{t+1} - cost*|a_t -
    a_{t-1}|`. The friction term is a function of the *action*: a cost charged
    as a constant every step shifts every action's reward identically and
    therefore cannot penalize turnover at all.
    """
    seed_everything(seed)
    torch_device = resolve_device(device)
    features = list(features)
    state_dim = len(features)

    dates = close.index
    split_date = dates[int(len(dates) * train_fraction)]

    # Standardize on training rows only.
    train_blocks = []
    for symbol, frame in feature_panel.items():
        block = frame.reindex(columns=features)
        block = block[block.index <= split_date].dropna()
        if len(block):
            train_blocks.append(block.to_numpy(dtype=np.float64))
    if not train_blocks:
        raise ValueError("no training rows for the SAC policy")
    standardizer = Standardizer.fit(np.concatenate(train_blocks))

    episodes: Dict[str, Dict[str, np.ndarray]] = {}
    for symbol, frame in feature_panel.items():
        if symbol not in close.columns:
            continue
        block = frame.reindex(columns=features).dropna()
        block = block[block.index <= split_date]
        if len(block) < 60:
            continue
        prices = close[symbol].reindex(block.index)
        forward = (prices.shift(-1) / prices - 1.0).to_numpy()
        episodes[symbol] = {
            "states": standardizer.transform(block.to_numpy(dtype=np.float64)),
            "forward": forward,
        }
    if not episodes:
        raise ValueError("no usable episodes for the SAC policy")

    actor = SACActor(state_dim, hidden_dim).to(torch_device)
    critic = TwinCritic(state_dim, hidden_dim).to(torch_device)
    critic_target = TwinCritic(state_dim, hidden_dim).to(torch_device)
    critic_target.load_state_dict(critic.state_dict())
    for p in critic_target.parameters():
        p.requires_grad_(False)

    actor_opt = torch.optim.Adam(actor.parameters(), lr=learning_rate)
    critic_opt = torch.optim.Adam(critic.parameters(), lr=learning_rate)
    log_alpha = torch.tensor(math.log(0.1), device=torch_device, requires_grad=True)
    alpha_opt = torch.optim.Adam([log_alpha], lr=learning_rate)
    target_entropy = -1.0

    buffer = ReplayBuffer(buffer_size, state_dim, seed=seed)
    history: List[Dict[str, float]] = []

    for epoch in range(1, epochs + 1):
        # Re-collect on-policy experience: training against a buffer collected
        # once means the actor only ever sees a random policy's decisions.
        actor.eval()
        with torch.no_grad():
            for episode in episodes.values():
                states = episode["states"]
                forward = episode["forward"]
                actions, _ = actor.sample(torch.as_tensor(states, device=torch_device))
                actions = actions.squeeze(-1).cpu().numpy()

                sortino = DifferentialSortino()
                previous = 0.0
                for t in range(len(states) - 1):
                    r = forward[t]
                    if not np.isfinite(r):
                        continue
                    a = float(actions[t])
                    net = a * float(r) - friction_cost * abs(a - previous)
                    previous = a
                    if t < 20:
                        sortino.warmup(net)
                        continue
                    buffer.push(states[t], a, sortino.update(net), states[t + 1])
        actor.train()

        if len(buffer) < batch_size:
            continue

        critic_total, actor_total = 0.0, 0.0
        for _ in range(gradient_steps):
            s, a, r, s2 = buffer.sample(batch_size)
            s = torch.as_tensor(s, device=torch_device)
            a = torch.as_tensor(a, device=torch_device)
            r = torch.as_tensor(r, device=torch_device)
            s2 = torch.as_tensor(s2, device=torch_device)
            alpha = log_alpha.exp().detach()

            with torch.no_grad():
                a2, logp2 = actor.sample(s2)
                q1t, q2t = critic_target(s2, a2)
                backup = r + gamma * (torch.min(q1t, q2t) - alpha * logp2)

            q1, q2 = critic(s, a)
            critic_loss = F.mse_loss(q1, backup) + F.mse_loss(q2, backup)
            critic_opt.zero_grad(set_to_none=True)
            critic_loss.backward()
            nn.utils.clip_grad_norm_(critic.parameters(), 1.0)
            critic_opt.step()

            new_a, logp = actor.sample(s)
            q1pi, q2pi = critic(s, new_a)
            actor_loss = (alpha * logp - torch.min(q1pi, q2pi)).mean()
            actor_opt.zero_grad(set_to_none=True)
            actor_loss.backward()
            nn.utils.clip_grad_norm_(actor.parameters(), 1.0)
            actor_opt.step()

            alpha_loss = -(log_alpha * (logp.detach() + target_entropy)).mean()
            alpha_opt.zero_grad(set_to_none=True)
            alpha_loss.backward()
            alpha_opt.step()

            with torch.no_grad():
                for p, tp in zip(critic.parameters(), critic_target.parameters()):
                    tp.mul_(1 - tau).add_(p, alpha=tau)

            critic_total += float(critic_loss.item())
            actor_total += float(actor_loss.item())

        history.append({
            "epoch": epoch,
            "critic_loss": critic_total / gradient_steps,
            "actor_loss": actor_total / gradient_steps,
            "alpha": float(log_alpha.exp().item()),
            "buffer": len(buffer),
        })
        if verbose and (epoch == 1 or epoch % 10 == 0):
            print(f"  epoch {epoch:3d}  critic {history[-1]['critic_loss']:.4f}  "
                  f"actor {history[-1]['actor_loss']:+.4f}  alpha {history[-1]['alpha']:.4f}")

    actor.eval()
    return {
        "actor": actor,
        "device": torch_device,
        "standardizer": standardizer,
        "features": features,
        "history": pd.DataFrame(history),
        "split_date": split_date,
    }


def sac_scores(
    trained: Dict[str, object],
    feature_panel: Dict[str, pd.DataFrame],
    close: pd.DataFrame,
    threshold: float = 0.5,
) -> pd.DataFrame:
    """Allocation weight per name per date, from the deterministic policy."""
    actor = trained["actor"]
    device = trained["device"]
    standardizer: Standardizer = trained["standardizer"]
    features = list(trained["features"])

    scores = pd.DataFrame(0.0, index=close.index, columns=close.columns)

    actor.eval()
    with torch.no_grad():
        for symbol, frame in feature_panel.items():
            if symbol not in close.columns:
                continue
            block = frame.reindex(columns=features).dropna()
            if block.empty:
                continue
            states = standardizer.transform(block.to_numpy(dtype=np.float64))
            weights = actor(torch.as_tensor(states, device=device)).squeeze(-1).cpu().numpy()
            scores.loc[block.index, symbol] = weights

    # Below the threshold the policy is not asking for a position; keeping those
    # weights would put a token holding in every name in the universe.
    return scores.where(scores >= threshold, 0.0)


# --- Visualization ------------------------------------------------------------


# A small, colour-blind-safe categorical palette (Okabe-Ito). Chosen so a
# multi-series chart stays readable in greyscale and for the ~8% of readers
# with a colour vision deficiency, which the default matplotlib cycle does not.
PALETTE = [
    "#0072B2", "#D55E00", "#009E73", "#CC79A7",
    "#E69F00", "#56B4E9", "#F0E442", "#000000",
]
GRID = {"color": "#CCCCCC", "linewidth": 0.6, "alpha": 0.7}

plt.rcParams.update({
    "figure.figsize": (11, 4.5),
    "figure.dpi": 110,
    "axes.grid": True,
    "axes.axisbelow": True,
    "axes.spines.top": False,
    "axes.spines.right": False,
    "axes.prop_cycle": plt.cycler(color=PALETTE),
    "font.size": 10,
    "legend.frameon": False,
})


def _pct_axis(ax) -> None:
    ax.yaxis.set_major_formatter(mticker.FuncFormatter(lambda v, _: f"{v:.0%}"))


def plot_prices(panel: Dict[str, pd.DataFrame], n: int = 8, title: str = "Price history") -> None:
    """Normalized price paths, so names of different absolute price compare."""
    fig, ax = plt.subplots()
    for symbol in list(sorted(panel))[:n]:
        close = panel[symbol]["close"].dropna()
        if close.empty:
            continue
        ax.plot(close.index, close / close.iloc[0], label=symbol, linewidth=1.2)
    ax.set_title(f"{title} (rebased to 1.0)")
    ax.set_ylabel("growth of 1")
    ax.grid(**GRID)
    ax.legend(ncol=4, fontsize=8)
    plt.tight_layout()
    plt.show()


def plot_data_quality(quality: pd.DataFrame) -> None:
    """Coverage and volatility side by side — the two things that invalidate a run."""
    fig, axes = plt.subplots(1, 2, figsize=(12, 4))

    order = quality.sort_values("coverage")
    axes[0].barh(order["symbol"], order["coverage"], color=PALETTE[0])
    axes[0].axvline(0.95, color=PALETTE[1], linestyle="--", linewidth=1,
                    label="95% of business days")
    axes[0].set_title("Session coverage")
    axes[0].set_xlabel("observed / expected business days")
    axes[0].legend(fontsize=8)
    axes[0].grid(**GRID)

    axes[1].scatter(quality["ann_vol"], quality["max_1d_move"],
                    color=PALETTE[2], s=28, alpha=0.85)
    for _, row in quality.iterrows():
        axes[1].annotate(row["symbol"], (row["ann_vol"], row["max_1d_move"]),
                         fontsize=6, alpha=0.7,
                         xytext=(3, 3), textcoords="offset points")
    axes[1].set_title("Volatility vs largest single-day move")
    axes[1].set_xlabel("annualized vol")
    axes[1].set_ylabel("max |1-day return|")
    axes[1].grid(**GRID)

    plt.tight_layout()
    plt.show()


def plot_equity(
    results: Dict[str, "BacktestResult"],
    benchmark: Optional[pd.Series] = None,
    title: str = "Equity curve",
    log_scale: bool = True,
) -> None:
    """Equity curves over drawdown — the two panels that matter, aligned in time."""
    fig, axes = plt.subplots(2, 1, figsize=(11, 7), sharex=True,
                             gridspec_kw={"height_ratios": [2.2, 1]})

    for i, (name, result) in enumerate(results.items()):
        equity = result.equity / result.equity.iloc[0]
        axes[0].plot(equity.index, equity, label=name,
                     color=PALETTE[i % len(PALETTE)], linewidth=1.4)
        axes[1].fill_between(result.drawdown.index, result.drawdown, 0,
                             color=PALETTE[i % len(PALETTE)], alpha=0.28)

    if benchmark is not None and len(benchmark):
        bench = (1.0 + benchmark.fillna(0.0)).cumprod()
        axes[0].plot(bench.index, bench / bench.iloc[0], label="benchmark",
                     color="#666666", linewidth=1.2, linestyle="--")

    axes[0].set_title(title)
    axes[0].set_ylabel("growth of 1")
    if log_scale:
        axes[0].set_yscale("log")
        axes[0].yaxis.set_major_formatter(mticker.FuncFormatter(lambda v, _: f"{v:.1f}x"))
    axes[0].grid(**GRID)
    axes[0].legend(ncol=3, fontsize=9)

    axes[1].set_title("Drawdown")
    axes[1].set_ylabel("peak-to-trough")
    _pct_axis(axes[1])
    axes[1].grid(**GRID)

    plt.tight_layout()
    plt.show()


def plot_return_profile(result: "BacktestResult", name: str = "strategy") -> None:
    """Distribution, rolling risk-adjusted return, and monthly seasonality."""
    fig, axes = plt.subplots(1, 3, figsize=(13.5, 3.8))

    returns = result.returns.dropna()

    axes[0].hist(returns, bins=60, color=PALETTE[0], alpha=0.85)
    axes[0].axvline(0, color="#444444", linewidth=1)
    axes[0].axvline(returns.mean(), color=PALETTE[1], linestyle="--", linewidth=1.2,
                    label=f"mean {returns.mean():.4f}")
    axes[0].set_title("Daily return distribution")
    axes[0].legend(fontsize=8)
    axes[0].grid(**GRID)

    window = min(126, max(21, len(returns) // 4))
    rolling = (returns.rolling(window).mean() / returns.rolling(window).std()) * np.sqrt(252)
    axes[1].plot(rolling.index, rolling, color=PALETTE[2], linewidth=1.2)
    axes[1].axhline(0, color="#444444", linewidth=1)
    axes[1].set_title(f"Rolling Sharpe ({window}d)")
    axes[1].grid(**GRID)

    monthly = returns.resample("ME").apply(lambda r: (1 + r).prod() - 1)
    colors = [PALETTE[2] if v >= 0 else PALETTE[1] for v in monthly]
    axes[2].bar(monthly.index, monthly, width=20, color=colors)
    axes[2].axhline(0, color="#444444", linewidth=1)
    axes[2].set_title("Monthly returns")
    _pct_axis(axes[2])
    axes[2].grid(**GRID)

    fig.suptitle(name, y=1.04, fontsize=11)
    plt.tight_layout()
    plt.show()


def plot_exposure(result: "BacktestResult", name: str = "strategy") -> None:
    """What the book actually held: gross exposure, breadth, and turnover."""
    fig, axes = plt.subplots(1, 3, figsize=(13.5, 3.6))

    gross = result.weights.sum(axis=1)
    axes[0].plot(gross.index, gross, color=PALETTE[0], linewidth=1.1)
    axes[0].set_title("Gross exposure")
    _pct_axis(axes[0])
    axes[0].grid(**GRID)

    breadth = (result.weights > 1e-6).sum(axis=1)
    axes[1].plot(breadth.index, breadth, color=PALETTE[3], linewidth=1.1)
    axes[1].set_title("Positions held")
    axes[1].grid(**GRID)

    cumulative_cost = result.costs.cumsum()
    axes[2].plot(cumulative_cost.index, cumulative_cost, color=PALETTE[1], linewidth=1.2)
    axes[2].set_title("Cumulative trading cost")
    _pct_axis(axes[2])
    axes[2].grid(**GRID)

    fig.suptitle(name, y=1.04, fontsize=11)
    plt.tight_layout()
    plt.show()


def plot_weight_heatmap(result: "BacktestResult", max_symbols: int = 25,
                        title: str = "Allocation over time") -> None:
    """Which names the book was in, and when."""
    weights = result.weights
    if weights.empty:
        print("no weights to plot")
        return

    top = weights.mean().sort_values(ascending=False).head(max_symbols).index
    matrix = weights[top].T

    fig, ax = plt.subplots(figsize=(12, max(3.2, 0.26 * len(top))))
    image = ax.imshow(matrix.to_numpy(), aspect="auto", cmap="viridis",
                      interpolation="nearest")
    ax.set_yticks(range(len(top)))
    ax.set_yticklabels(top, fontsize=7)

    ticks = np.linspace(0, matrix.shape[1] - 1, min(10, matrix.shape[1])).astype(int)
    ax.set_xticks(ticks)
    ax.set_xticklabels([matrix.columns[i].strftime("%Y-%m") for i in ticks],
                       rotation=45, ha="right", fontsize=8)
    ax.set_title(title)
    ax.grid(False)
    fig.colorbar(image, ax=ax, label="weight", shrink=0.8)
    plt.tight_layout()
    plt.show()


def plot_training_curve(history: pd.DataFrame, metrics: Sequence[str],
                        title: str = "Training") -> None:
    """One panel per tracked metric, sharing the epoch axis."""
    metrics = [m for m in metrics if m in history.columns]
    if not metrics:
        print("no metrics to plot")
        return

    fig, axes = plt.subplots(1, len(metrics), figsize=(4.4 * len(metrics), 3.4))
    if len(metrics) == 1:
        axes = [axes]

    for ax, metric, colour in zip(axes, metrics, PALETTE):
        ax.plot(history["epoch"], history[metric], color=colour, linewidth=1.4)
        ax.set_title(metric)
        ax.set_xlabel("epoch")
        ax.grid(**GRID)

    fig.suptitle(title, y=1.05, fontsize=11)
    plt.tight_layout()
    plt.show()


def plot_stats_table(stats: pd.DataFrame, title: str = "Performance") -> None:
    """Bar comparison of the statistics that are comparable across strategies."""
    columns = [c for c in ("sharpe", "sortino", "cagr", "max_drawdown") if c in stats.columns]
    if not columns:
        print("nothing comparable to plot")
        return

    fig, axes = plt.subplots(1, len(columns), figsize=(3.4 * len(columns), 3.4))
    if len(columns) == 1:
        axes = [axes]

    for ax, column in zip(axes, columns):
        values = stats[column].sort_values()
        colors = [PALETTE[1] if v < 0 else PALETTE[0] for v in values]
        ax.barh(values.index, values, color=colors)
        ax.set_title(column)
        ax.axvline(0, color="#444444", linewidth=1)
        ax.tick_params(labelsize=8)
        ax.grid(**GRID)

    fig.suptitle(title, y=1.04, fontsize=11)
    plt.tight_layout()
    plt.show()
